//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ResumeBuilder.XPO.Database
{

    public partial class Certification : XPLiteObject
    {
        int fRid;
        [Key(true)]
        public int Rid
        {
            get { return fRid; }
            set { SetPropertyValue<int>(nameof(Rid), ref fRid, value); }
        }
        JobSeekerResume fResume_ID;
        [Association(@"CertificationReferencesJobSeekerResume")]
        public JobSeekerResume Resume_ID
        {
            get { return fResume_ID; }
            set { SetPropertyValue<JobSeekerResume>(nameof(Resume_ID), ref fResume_ID, value); }
        }
        string fCertificationName;
        [Size(200)]
        public string CertificationName
        {
            get { return fCertificationName; }
            set { SetPropertyValue<string>(nameof(CertificationName), ref fCertificationName, value); }
        }
        int fCertificateType;
        public int CertificateType
        {
            get { return fCertificateType; }
            set { SetPropertyValue<int>(nameof(CertificateType), ref fCertificateType, value); }
        }
        int fCityId;
        public int CityId
        {
            get { return fCityId; }
            set { SetPropertyValue<int>(nameof(CityId), ref fCityId, value); }
        }
        string fInstitute;
        [Size(SizeAttribute.Unlimited)]
        public string Institute
        {
            get { return fInstitute; }
            set { SetPropertyValue<string>(nameof(Institute), ref fInstitute, value); }
        }
        DateTime fFromDate;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime FromDate
        {
            get { return fFromDate; }
            set { SetPropertyValue<DateTime>(nameof(FromDate), ref fFromDate, value); }
        }
        DateTime fToDate;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime ToDate
        {
            get { return fToDate; }
            set { SetPropertyValue<DateTime>(nameof(ToDate), ref fToDate, value); }
        }
        string fScore;
        [Size(50)]
        public string Score
        {
            get { return fScore; }
            set { SetPropertyValue<string>(nameof(Score), ref fScore, value); }
        }
        bool fIsDeleted1;
        [Persistent(@"IsDeleted")]
        [ColumnDbDefaultValue("((0))")]
        public bool IsDeleted1
        {
            get { return fIsDeleted1; }
            set { SetPropertyValue<bool>(nameof(IsDeleted1), ref fIsDeleted1, value); }
        }
        int fInstituteId;
        public int InstituteId
        {
            get { return fInstituteId; }
            set { SetPropertyValue<int>(nameof(InstituteId), ref fInstituteId, value); }
        }
        int fCountryId;
        public int CountryId
        {
            get { return fCountryId; }
            set { SetPropertyValue<int>(nameof(CountryId), ref fCountryId, value); }
        }
    }

}
