//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ResumeBuilder.XPO.Database
{

    public partial class Education : XPLiteObject
    {
        long fRID;
        [Key(true)]
        public long RID
        {
            get { return fRID; }
            set { SetPropertyValue<long>(nameof(RID), ref fRID, value); }
        }
        JobSeekerResume fResume_ID;
        [Association(@"EducationReferencesJobSeekerResume")]
        public JobSeekerResume Resume_ID
        {
            get { return fResume_ID; }
            set { SetPropertyValue<JobSeekerResume>(nameof(Resume_ID), ref fResume_ID, value); }
        }
        int fEducation_Group_ID;
        public int Education_Group_ID
        {
            get { return fEducation_Group_ID; }
            set { SetPropertyValue<int>(nameof(Education_Group_ID), ref fEducation_Group_ID, value); }
        }
        int fEducation_Type_ID;
        public int Education_Type_ID
        {
            get { return fEducation_Type_ID; }
            set { SetPropertyValue<int>(nameof(Education_Type_ID), ref fEducation_Type_ID, value); }
        }
        int fUniversity_Type_ID;
        public int University_Type_ID
        {
            get { return fUniversity_Type_ID; }
            set { SetPropertyValue<int>(nameof(University_Type_ID), ref fUniversity_Type_ID, value); }
        }
        int fUniversity_ID;
        public int University_ID
        {
            get { return fUniversity_ID; }
            set { SetPropertyValue<int>(nameof(University_ID), ref fUniversity_ID, value); }
        }
        int fCourse_ID;
        public int Course_ID
        {
            get { return fCourse_ID; }
            set { SetPropertyValue<int>(nameof(Course_ID), ref fCourse_ID, value); }
        }
        int fEducation_Major_ID;
        public int Education_Major_ID
        {
            get { return fEducation_Major_ID; }
            set { SetPropertyValue<int>(nameof(Education_Major_ID), ref fEducation_Major_ID, value); }
        }
        int fEmirate_ID;
        public int Emirate_ID
        {
            get { return fEmirate_ID; }
            set { SetPropertyValue<int>(nameof(Emirate_ID), ref fEmirate_ID, value); }
        }
        string fGrade;
        [Size(50)]
        public string Grade
        {
            get { return fGrade; }
            set { SetPropertyValue<string>(nameof(Grade), ref fGrade, value); }
        }
        DateTime fToYear;
        public DateTime ToYear
        {
            get { return fToYear; }
            set { SetPropertyValue<DateTime>(nameof(ToYear), ref fToYear, value); }
        }
        DateTime fFromYear;
        public DateTime FromYear
        {
            get { return fFromYear; }
            set { SetPropertyValue<DateTime>(nameof(FromYear), ref fFromYear, value); }
        }
        string fInstitute;
        [Size(500)]
        public string Institute
        {
            get { return fInstitute; }
            set { SetPropertyValue<string>(nameof(Institute), ref fInstitute, value); }
        }
        bool fIsDeleted1;
        [Persistent(@"IsDeleted")]
        [ColumnDbDefaultValue("((0))")]
        public bool IsDeleted1
        {
            get { return fIsDeleted1; }
            set { SetPropertyValue<bool>(nameof(IsDeleted1), ref fIsDeleted1, value); }
        }
        bool fIsThisHigestQualication;
        [ColumnDbDefaultValue("((0))")]
        public bool IsThisHigestQualication
        {
            get { return fIsThisHigestQualication; }
            set { SetPropertyValue<bool>(nameof(IsThisHigestQualication), ref fIsThisHigestQualication, value); }
        }
        int fCategory_ID;
        public int Category_ID
        {
            get { return fCategory_ID; }
            set { SetPropertyValue<int>(nameof(Category_ID), ref fCategory_ID, value); }
        }
        int fGrade_Category_ID;
        public int Grade_Category_ID
        {
            get { return fGrade_Category_ID; }
            set { SetPropertyValue<int>(nameof(Grade_Category_ID), ref fGrade_Category_ID, value); }
        }
        int fLocation_ID;
        public int Location_ID
        {
            get { return fLocation_ID; }
            set { SetPropertyValue<int>(nameof(Location_ID), ref fLocation_ID, value); }
        }
    }

}
