//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ResumeBuilder.XPO.Database
{

    public partial class Employer : XPLiteObject
    {
        long fRID;
        [Key(true)]
        public long RID
        {
            get { return fRID; }
            set { SetPropertyValue<long>(nameof(RID), ref fRID, value); }
        }
        JobSeekerResume fResume_ID;
        [Association(@"EmployerReferencesJobSeekerResume")]
        public JobSeekerResume Resume_ID
        {
            get { return fResume_ID; }
            set { SetPropertyValue<JobSeekerResume>(nameof(Resume_ID), ref fResume_ID, value); }
        }
        int fParticular_ID;
        public int Particular_ID
        {
            get { return fParticular_ID; }
            set { SetPropertyValue<int>(nameof(Particular_ID), ref fParticular_ID, value); }
        }
        long fEmployer_ID;
        public long Employer_ID
        {
            get { return fEmployer_ID; }
            set { SetPropertyValue<long>(nameof(Employer_ID), ref fEmployer_ID, value); }
        }
        string fEmployerAddress;
        [Size(SizeAttribute.Unlimited)]
        public string EmployerAddress
        {
            get { return fEmployerAddress; }
            set { SetPropertyValue<string>(nameof(EmployerAddress), ref fEmployerAddress, value); }
        }
        string fPhone;
        [Size(25)]
        public string Phone
        {
            get { return fPhone; }
            set { SetPropertyValue<string>(nameof(Phone), ref fPhone, value); }
        }
        string fEmployer_Code_No;
        [Size(15)]
        public string Employer_Code_No
        {
            get { return fEmployer_Code_No; }
            set { SetPropertyValue<string>(nameof(Employer_Code_No), ref fEmployer_Code_No, value); }
        }
        long fDesigination_ID;
        public long Desigination_ID
        {
            get { return fDesigination_ID; }
            set { SetPropertyValue<long>(nameof(Desigination_ID), ref fDesigination_ID, value); }
        }
        string fDepartment;
        public string Department
        {
            get { return fDepartment; }
            set { SetPropertyValue<string>(nameof(Department), ref fDepartment, value); }
        }
        DateTime fFromDate;
        public DateTime FromDate
        {
            get { return fFromDate; }
            set { SetPropertyValue<DateTime>(nameof(FromDate), ref fFromDate, value); }
        }
        DateTime fToDate;
        public DateTime ToDate
        {
            get { return fToDate; }
            set { SetPropertyValue<DateTime>(nameof(ToDate), ref fToDate, value); }
        }
        bool fIsDeleted1;
        [Persistent(@"IsDeleted")]
        [ColumnDbDefaultValue("((0))")]
        public bool IsDeleted1
        {
            get { return fIsDeleted1; }
            set { SetPropertyValue<bool>(nameof(IsDeleted1), ref fIsDeleted1, value); }
        }
        bool fIsThisMyCurrentRole;
        [ColumnDbDefaultValue("((0))")]
        public bool IsThisMyCurrentRole
        {
            get { return fIsThisMyCurrentRole; }
            set { SetPropertyValue<bool>(nameof(IsThisMyCurrentRole), ref fIsThisMyCurrentRole, value); }
        }
        string fRolesAndResposibilites;
        [Size(2000)]
        public string RolesAndResposibilites
        {
            get { return fRolesAndResposibilites; }
            set { SetPropertyValue<string>(nameof(RolesAndResposibilites), ref fRolesAndResposibilites, value); }
        }
        string fAchievements;
        [Size(800)]
        public string Achievements
        {
            get { return fAchievements; }
            set { SetPropertyValue<string>(nameof(Achievements), ref fAchievements, value); }
        }
        int fid;
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        int fEmployer_Location_ID;
        public int Employer_Location_ID
        {
            get { return fEmployer_Location_ID; }
            set { SetPropertyValue<int>(nameof(Employer_Location_ID), ref fEmployer_Location_ID, value); }
        }
        int fJob_Industry_Type_ID;
        public int Job_Industry_Type_ID
        {
            get { return fJob_Industry_Type_ID; }
            set { SetPropertyValue<int>(nameof(Job_Industry_Type_ID), ref fJob_Industry_Type_ID, value); }
        }
        int fJob_Role_ID;
        public int Job_Role_ID
        {
            get { return fJob_Role_ID; }
            set { SetPropertyValue<int>(nameof(Job_Role_ID), ref fJob_Role_ID, value); }
        }
        int fJob_Location_ID;
        public int Job_Location_ID
        {
            get { return fJob_Location_ID; }
            set { SetPropertyValue<int>(nameof(Job_Location_ID), ref fJob_Location_ID, value); }
        }
        int fEmployment_Type_ID;
        public int Employment_Type_ID
        {
            get { return fEmployment_Type_ID; }
            set { SetPropertyValue<int>(nameof(Employment_Type_ID), ref fEmployment_Type_ID, value); }
        }
    }

}
