//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ResumeBuilder.XPO.Database
{

    public partial class JobSeekerGrieveance : XPLiteObject
    {
        long fRID;
        [Key(true)]
        public long RID
        {
            get { return fRID; }
            set { SetPropertyValue<long>(nameof(RID), ref fRID, value); }
        }
        long fresumeid;
        public long resumeid
        {
            get { return fresumeid; }
            set { SetPropertyValue<long>(nameof(resumeid), ref fresumeid, value); }
        }
        short fstatus;
        public short status
        {
            get { return fstatus; }
            set { SetPropertyValue<short>(nameof(status), ref fstatus, value); }
        }
        string fticketno;
        public string ticketno
        {
            get { return fticketno; }
            set { SetPropertyValue<string>(nameof(ticketno), ref fticketno, value); }
        }
        string fcomment;
        [Size(300)]
        public string comment
        {
            get { return fcomment; }
            set { SetPropertyValue<string>(nameof(comment), ref fcomment, value); }
        }
        string fdocument;
        [Size(SizeAttribute.Unlimited)]
        public string document
        {
            get { return fdocument; }
            set { SetPropertyValue<string>(nameof(document), ref fdocument, value); }
        }
        DateTime fcreatedate;
        [ColumnDbDefaultValue("(getutcdate())")]
        public DateTime createdate
        {
            get { return fcreatedate; }
            set { SetPropertyValue<DateTime>(nameof(createdate), ref fcreatedate, value); }
        }
        string fcreateduserid;
        [Size(200)]
        public string createduserid
        {
            get { return fcreateduserid; }
            set { SetPropertyValue<string>(nameof(createduserid), ref fcreateduserid, value); }
        }
        DateTime fmodifieddate;
        public DateTime modifieddate
        {
            get { return fmodifieddate; }
            set { SetPropertyValue<DateTime>(nameof(modifieddate), ref fmodifieddate, value); }
        }
        string fmodifieduserid;
        [Size(200)]
        public string modifieduserid
        {
            get { return fmodifieduserid; }
            set { SetPropertyValue<string>(nameof(modifieduserid), ref fmodifieduserid, value); }
        }
        int fid;
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        string fMongoDBUniqueId;
        [Size(45)]
        public string MongoDBUniqueId
        {
            get { return fMongoDBUniqueId; }
            set { SetPropertyValue<string>(nameof(MongoDBUniqueId), ref fMongoDBUniqueId, value); }
        }
        string fFileName;
        [Size(150)]
        public string FileName
        {
            get { return fFileName; }
            set { SetPropertyValue<string>(nameof(FileName), ref fFileName, value); }
        }
        bool fIs_Deleted;
        [ColumnDbDefaultValue("((0))")]
        public bool Is_Deleted
        {
            get { return fIs_Deleted; }
            set { SetPropertyValue<bool>(nameof(Is_Deleted), ref fIs_Deleted, value); }
        }
    }

}
