//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ResumeBuilder.XPO.Database
{

    public partial class JobSeekerAttachment : XPLiteObject
    {
        int fRID;
        [Key(true)]
        public int RID
        {
            get { return fRID; }
            set { SetPropertyValue<int>(nameof(RID), ref fRID, value); }
        }
        long fResume_ID;
        public long Resume_ID
        {
            get { return fResume_ID; }
            set { SetPropertyValue<long>(nameof(Resume_ID), ref fResume_ID, value); }
        }
        string fMongoDBUniqueId;
        [Size(45)]
        public string MongoDBUniqueId
        {
            get { return fMongoDBUniqueId; }
            set { SetPropertyValue<string>(nameof(MongoDBUniqueId), ref fMongoDBUniqueId, value); }
        }
        int fDocumentType_ID;
        public int DocumentType_ID
        {
            get { return fDocumentType_ID; }
            set { SetPropertyValue<int>(nameof(DocumentType_ID), ref fDocumentType_ID, value); }
        }
        string fFileName;
        [Size(150)]
        public string FileName
        {
            get { return fFileName; }
            set { SetPropertyValue<string>(nameof(FileName), ref fFileName, value); }
        }
        DateTime fFileDateTime;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime FileDateTime
        {
            get { return fFileDateTime; }
            set { SetPropertyValue<DateTime>(nameof(FileDateTime), ref fFileDateTime, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        bool fIsDeleted1;
        [Persistent(@"IsDeleted")]
        [ColumnDbDefaultValue("((0))")]
        public bool IsDeleted1
        {
            get { return fIsDeleted1; }
            set { SetPropertyValue<bool>(nameof(IsDeleted1), ref fIsDeleted1, value); }
        }
    }

}
