//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ResumeBuilder.XPO.Database
{

    public partial class JobsSeekerStatus : XPLiteObject
    {
        int fRID;
        [Key(true)]
        public int RID
        {
            get { return fRID; }
            set { SetPropertyValue<int>(nameof(RID), ref fRID, value); }
        }
        int fStatus_ID;
        public int Status_ID
        {
            get { return fStatus_ID; }
            set { SetPropertyValue<int>(nameof(Status_ID), ref fStatus_ID, value); }
        }
        int fReason_ID;
        public int Reason_ID
        {
            get { return fReason_ID; }
            set { SetPropertyValue<int>(nameof(Reason_ID), ref fReason_ID, value); }
        }
        long fResume_ID;
        public long Resume_ID
        {
            get { return fResume_ID; }
            set { SetPropertyValue<long>(nameof(Resume_ID), ref fResume_ID, value); }
        }
        DateTime fStatusUpdateDateTime;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime StatusUpdateDateTime
        {
            get { return fStatusUpdateDateTime; }
            set { SetPropertyValue<DateTime>(nameof(StatusUpdateDateTime), ref fStatusUpdateDateTime, value); }
        }
        string fUserId;
        [Size(450)]
        public string UserId
        {
            get { return fUserId; }
            set { SetPropertyValue<string>(nameof(UserId), ref fUserId, value); }
        }
        string fNotes;
        [Size(1000)]
        public string Notes
        {
            get { return fNotes; }
            set { SetPropertyValue<string>(nameof(Notes), ref fNotes, value); }
        }
    }

}
