//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ResumeBuilder.XPO.Database
{

    public partial class JobSeekerResume : XPLiteObject
    {
        long fRID;
        [Key(true)]
        public long RID
        {
            get { return fRID; }
            set { SetPropertyValue<long>(nameof(RID), ref fRID, value); }
        }
        string fFirstName;
        [Size(25)]
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>(nameof(FirstName), ref fFirstName, value); }
        }
        string fMiddleName;
        [Size(25)]
        public string MiddleName
        {
            get { return fMiddleName; }
            set { SetPropertyValue<string>(nameof(MiddleName), ref fMiddleName, value); }
        }
        string fThridName;
        [Size(25)]
        public string ThridName
        {
            get { return fThridName; }
            set { SetPropertyValue<string>(nameof(ThridName), ref fThridName, value); }
        }
        string fLastName;
        [Size(25)]
        public string LastName
        {
            get { return fLastName; }
            set { SetPropertyValue<string>(nameof(LastName), ref fLastName, value); }
        }
        string fFirstNameAr;
        [Size(150)]
        public string FirstNameAr
        {
            get { return fFirstNameAr; }
            set { SetPropertyValue<string>(nameof(FirstNameAr), ref fFirstNameAr, value); }
        }
        string fMiddleNameAr;
        [Size(25)]
        public string MiddleNameAr
        {
            get { return fMiddleNameAr; }
            set { SetPropertyValue<string>(nameof(MiddleNameAr), ref fMiddleNameAr, value); }
        }
        string fThridNameAr;
        [Size(25)]
        public string ThridNameAr
        {
            get { return fThridNameAr; }
            set { SetPropertyValue<string>(nameof(ThridNameAr), ref fThridNameAr, value); }
        }
        string fLastNameAr;
        [Size(150)]
        public string LastNameAr
        {
            get { return fLastNameAr; }
            set { SetPropertyValue<string>(nameof(LastNameAr), ref fLastNameAr, value); }
        }
        string fFamilyNameAr;
        [Size(150)]
        public string FamilyNameAr
        {
            get { return fFamilyNameAr; }
            set { SetPropertyValue<string>(nameof(FamilyNameAr), ref fFamilyNameAr, value); }
        }
        string fFamilyName;
        [Size(150)]
        public string FamilyName
        {
            get { return fFamilyName; }
            set { SetPropertyValue<string>(nameof(FamilyName), ref fFamilyName, value); }
        }
        int fSalutation;
        public int Salutation
        {
            get { return fSalutation; }
            set { SetPropertyValue<int>(nameof(Salutation), ref fSalutation, value); }
        }
        int fGenderId;
        public int GenderId
        {
            get { return fGenderId; }
            set { SetPropertyValue<int>(nameof(GenderId), ref fGenderId, value); }
        }
        DateTime fDOB;
        public DateTime DOB
        {
            get { return fDOB; }
            set { SetPropertyValue<DateTime>(nameof(DOB), ref fDOB, value); }
        }
        int fPlaceOfBirth;
        public int PlaceOfBirth
        {
            get { return fPlaceOfBirth; }
            set { SetPropertyValue<int>(nameof(PlaceOfBirth), ref fPlaceOfBirth, value); }
        }
        int fMartialStatus;
        public int MartialStatus
        {
            get { return fMartialStatus; }
            set { SetPropertyValue<int>(nameof(MartialStatus), ref fMartialStatus, value); }
        }
        string fKAQNo;
        [Size(50)]
        public string KAQNo
        {
            get { return fKAQNo; }
            set { SetPropertyValue<string>(nameof(KAQNo), ref fKAQNo, value); }
        }
        string fFamilyNo;
        [Size(50)]
        public string FamilyNo
        {
            get { return fFamilyNo; }
            set { SetPropertyValue<string>(nameof(FamilyNo), ref fFamilyNo, value); }
        }
        string fTownNo;
        [Size(50)]
        public string TownNo
        {
            get { return fTownNo; }
            set { SetPropertyValue<string>(nameof(TownNo), ref fTownNo, value); }
        }
        string fKAQPageNo;
        [Size(50)]
        public string KAQPageNo
        {
            get { return fKAQPageNo; }
            set { SetPropertyValue<string>(nameof(KAQPageNo), ref fKAQPageNo, value); }
        }
        string fEmiratesId;
        [Size(50)]
        public string EmiratesId
        {
            get { return fEmiratesId; }
            set { SetPropertyValue<string>(nameof(EmiratesId), ref fEmiratesId, value); }
        }
        DateTime fEmiratesIdExpiryDate;
        public DateTime EmiratesIdExpiryDate
        {
            get { return fEmiratesIdExpiryDate; }
            set { SetPropertyValue<DateTime>(nameof(EmiratesIdExpiryDate), ref fEmiratesIdExpiryDate, value); }
        }
        string fPassportNumber;
        [Size(50)]
        public string PassportNumber
        {
            get { return fPassportNumber; }
            set { SetPropertyValue<string>(nameof(PassportNumber), ref fPassportNumber, value); }
        }
        int fPassportPlaceOfIssue;
        public int PassportPlaceOfIssue
        {
            get { return fPassportPlaceOfIssue; }
            set { SetPropertyValue<int>(nameof(PassportPlaceOfIssue), ref fPassportPlaceOfIssue, value); }
        }
        string fJobSeekerID;
        [Size(50)]
        public string JobSeekerID
        {
            get { return fJobSeekerID; }
            set { SetPropertyValue<string>(nameof(JobSeekerID), ref fJobSeekerID, value); }
        }
        int fEmirates;
        public int Emirates
        {
            get { return fEmirates; }
            set { SetPropertyValue<int>(nameof(Emirates), ref fEmirates, value); }
        }
        int fCityId;
        public int CityId
        {
            get { return fCityId; }
            set { SetPropertyValue<int>(nameof(CityId), ref fCityId, value); }
        }
        int fLocationId;
        public int LocationId
        {
            get { return fLocationId; }
            set { SetPropertyValue<int>(nameof(LocationId), ref fLocationId, value); }
        }
        string fPOBoxNo;
        [Size(10)]
        public string POBoxNo
        {
            get { return fPOBoxNo; }
            set { SetPropertyValue<string>(nameof(POBoxNo), ref fPOBoxNo, value); }
        }
        int fPOBoxCityId;
        public int POBoxCityId
        {
            get { return fPOBoxCityId; }
            set { SetPropertyValue<int>(nameof(POBoxCityId), ref fPOBoxCityId, value); }
        }
        string fMobilePhone;
        [Size(45)]
        public string MobilePhone
        {
            get { return fMobilePhone; }
            set { SetPropertyValue<string>(nameof(MobilePhone), ref fMobilePhone, value); }
        }
        string fLandLine;
        [Size(45)]
        public string LandLine
        {
            get { return fLandLine; }
            set { SetPropertyValue<string>(nameof(LandLine), ref fLandLine, value); }
        }
        string fEmailId;
        [Size(55)]
        public string EmailId
        {
            get { return fEmailId; }
            set { SetPropertyValue<string>(nameof(EmailId), ref fEmailId, value); }
        }
        string fPrimaryContact;
        [Size(SizeAttribute.Unlimited)]
        public string PrimaryContact
        {
            get { return fPrimaryContact; }
            set { SetPropertyValue<string>(nameof(PrimaryContact), ref fPrimaryContact, value); }
        }
        string fUnifiedNumber;
        [Size(50)]
        public string UnifiedNumber
        {
            get { return fUnifiedNumber; }
            set { SetPropertyValue<string>(nameof(UnifiedNumber), ref fUnifiedNumber, value); }
        }
        string fNotes;
        [Size(SizeAttribute.Unlimited)]
        public string Notes
        {
            get { return fNotes; }
            set { SetPropertyValue<string>(nameof(Notes), ref fNotes, value); }
        }
        bool fIsDeleted1;
        [Persistent(@"IsDeleted")]
        [ColumnDbDefaultValue("((0))")]
        public bool IsDeleted1
        {
            get { return fIsDeleted1; }
            set { SetPropertyValue<bool>(nameof(IsDeleted1), ref fIsDeleted1, value); }
        }
        string fMilitaryServiceBatch;
        [Size(200)]
        public string MilitaryServiceBatch
        {
            get { return fMilitaryServiceBatch; }
            set { SetPropertyValue<string>(nameof(MilitaryServiceBatch), ref fMilitaryServiceBatch, value); }
        }
        int fMilitaryServiceStatus;
        public int MilitaryServiceStatus
        {
            get { return fMilitaryServiceStatus; }
            set { SetPropertyValue<int>(nameof(MilitaryServiceStatus), ref fMilitaryServiceStatus, value); }
        }
        DateTime fMilitaryServiceFromDate;
        public DateTime MilitaryServiceFromDate
        {
            get { return fMilitaryServiceFromDate; }
            set { SetPropertyValue<DateTime>(nameof(MilitaryServiceFromDate), ref fMilitaryServiceFromDate, value); }
        }
        DateTime fMilitaryServiceToDate;
        public DateTime MilitaryServiceToDate
        {
            get { return fMilitaryServiceToDate; }
            set { SetPropertyValue<DateTime>(nameof(MilitaryServiceToDate), ref fMilitaryServiceToDate, value); }
        }
        int fid;
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        int fresumestatus;
        public int resumestatus
        {
            get { return fresumestatus; }
            set { SetPropertyValue<int>(nameof(resumestatus), ref fresumestatus, value); }
        }
        string fTwitter;
        [Size(75)]
        public string Twitter
        {
            get { return fTwitter; }
            set { SetPropertyValue<string>(nameof(Twitter), ref fTwitter, value); }
        }
        string fLinkedin;
        [Size(75)]
        public string Linkedin
        {
            get { return fLinkedin; }
            set { SetPropertyValue<string>(nameof(Linkedin), ref fLinkedin, value); }
        }
        string fAddress;
        [Size(SizeAttribute.Unlimited)]
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        string ffullArabicName;
        [Size(75)]
        public string fullArabicName
        {
            get { return ffullArabicName; }
            set { SetPropertyValue<string>(nameof(fullArabicName), ref ffullArabicName, value); }
        }
        string ffullEnglishName;
        [Size(75)]
        public string fullEnglishName
        {
            get { return ffullEnglishName; }
            set { SetPropertyValue<string>(nameof(fullEnglishName), ref ffullEnglishName, value); }
        }
        DateTime fpassportexpirydate;
        public DateTime passportexpirydate
        {
            get { return fpassportexpirydate; }
            set { SetPropertyValue<DateTime>(nameof(passportexpirydate), ref fpassportexpirydate, value); }
        }
        DateTime fpassportissueDate;
        public DateTime passportissueDate
        {
            get { return fpassportissueDate; }
            set { SetPropertyValue<DateTime>(nameof(passportissueDate), ref fpassportissueDate, value); }
        }
        string fedbarahNumber;
        [Size(75)]
        public string edbarahNumber
        {
            get { return fedbarahNumber; }
            set { SetPropertyValue<string>(nameof(edbarahNumber), ref fedbarahNumber, value); }
        }
        string fuuid;
        [Size(75)]
        public string uuid
        {
            get { return fuuid; }
            set { SetPropertyValue<string>(nameof(uuid), ref fuuid, value); }
        }
        string fusername;
        [Size(75)]
        public string username
        {
            get { return fusername; }
            set { SetPropertyValue<string>(nameof(username), ref fusername, value); }
        }
        string ffamilyBookNumber;
        [Size(75)]
        public string familyBookNumber
        {
            get { return ffamilyBookNumber; }
            set { SetPropertyValue<string>(nameof(familyBookNumber), ref ffamilyBookNumber, value); }
        }
        string ffamilybookpagenumber;
        [Size(75)]
        public string familybookpagenumber
        {
            get { return ffamilybookpagenumber; }
            set { SetPropertyValue<string>(nameof(familybookpagenumber), ref ffamilybookpagenumber, value); }
        }
        string fusertype;
        [Size(75)]
        public string usertype
        {
            get { return fusertype; }
            set { SetPropertyValue<string>(nameof(usertype), ref fusertype, value); }
        }
        string fCreatedUserID;
        [Size(75)]
        public string CreatedUserID
        {
            get { return fCreatedUserID; }
            set { SetPropertyValue<string>(nameof(CreatedUserID), ref fCreatedUserID, value); }
        }
        DateTime fEmiratesidissueDate;
        public DateTime EmiratesidissueDate
        {
            get { return fEmiratesidissueDate; }
            set { SetPropertyValue<DateTime>(nameof(EmiratesidissueDate), ref fEmiratesidissueDate, value); }
        }
        long fCountryID;
        public long CountryID
        {
            get { return fCountryID; }
            set { SetPropertyValue<long>(nameof(CountryID), ref fCountryID, value); }
        }
        bool fisspeciallyabled;
        public bool isspeciallyabled
        {
            get { return fisspeciallyabled; }
            set { SetPropertyValue<bool>(nameof(isspeciallyabled), ref fisspeciallyabled, value); }
        }
        DateTime fLastUpdateDate;
        public DateTime LastUpdateDate
        {
            get { return fLastUpdateDate; }
            set { SetPropertyValue<DateTime>(nameof(LastUpdateDate), ref fLastUpdateDate, value); }
        }
        string fLastModifiedUserID;
        [Size(75)]
        public string LastModifiedUserID
        {
            get { return fLastModifiedUserID; }
            set { SetPropertyValue<string>(nameof(LastModifiedUserID), ref fLastModifiedUserID, value); }
        }
        bool fIsCvCompletion;
        [ColumnDbDefaultValue("((0))")]
        public bool IsCvCompletion
        {
            get { return fIsCvCompletion; }
            set { SetPropertyValue<bool>(nameof(IsCvCompletion), ref fIsCvCompletion, value); }
        }
        DateTime fCreatedDate;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime CreatedDate
        {
            get { return fCreatedDate; }
            set { SetPropertyValue<DateTime>(nameof(CreatedDate), ref fCreatedDate, value); }
        }
        [Association(@"CertificationReferencesJobSeekerResume")]
        public XPCollection<Certification> Certifications { get { return GetCollection<Certification>(nameof(Certifications)); } }
        [Association(@"EducationReferencesJobSeekerResume")]
        public XPCollection<Education> Educations { get { return GetCollection<Education>(nameof(Educations)); } }
        [Association(@"EmployerReferencesJobSeekerResume")]
        public XPCollection<Employer> Employers { get { return GetCollection<Employer>(nameof(Employers)); } }
        [Association(@"NotesReferencesJobSeekerResume")]
        public XPCollection<Notes> NotesCollection { get { return GetCollection<Notes>(nameof(NotesCollection)); } }
        [Association(@"TrainingReferencesJobSeekerResume")]
        public XPCollection<Training> Trainings { get { return GetCollection<Training>(nameof(Trainings)); } }
        [Association(@"OccupationReferencesJobSeekerResume")]
        public XPCollection<Occupation> Occupations { get { return GetCollection<Occupation>(nameof(Occupations)); } }
        [Association(@"ToolsKnowledgeReferencesJobSeekerResume")]
        public XPCollection<ToolsKnowledge> ToolsKnowledges { get { return GetCollection<ToolsKnowledge>(nameof(ToolsKnowledges)); } }
        [Association(@"JobSeekerLanguagesReferencesJobSeekerResume")]
        public XPCollection<JobSeekerLanguages> JobSeekerLanguagesCollection { get { return GetCollection<JobSeekerLanguages>(nameof(JobSeekerLanguagesCollection)); } }
        [Association(@"JobSeekerPodReferencesJobSeekerResume")]
        public XPCollection<JobSeekerPod> JobSeekerPods { get { return GetCollection<JobSeekerPod>(nameof(JobSeekerPods)); } }
    }

}
