//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ResumeBuilder.XPO.Database
{

    public partial class JobSeekerPod : XPLiteObject
    {
        int fRId;
        [Key(true)]
        public int RId
        {
            get { return fRId; }
            set { SetPropertyValue<int>(nameof(RId), ref fRId, value); }
        }
        JobSeekerResume fResume_ID;
        [Association(@"JobSeekerPodReferencesJobSeekerResume")]
        public JobSeekerResume Resume_ID
        {
            get { return fResume_ID; }
            set { SetPropertyValue<JobSeekerResume>(nameof(Resume_ID), ref fResume_ID, value); }
        }
        int fSpeicalNeeds_ID;
        public int SpeicalNeeds_ID
        {
            get { return fSpeicalNeeds_ID; }
            set { SetPropertyValue<int>(nameof(SpeicalNeeds_ID), ref fSpeicalNeeds_ID, value); }
        }
        bool fIs_Deleted;
        [ColumnDbDefaultValue("((0))")]
        public bool Is_Deleted
        {
            get { return fIs_Deleted; }
            set { SetPropertyValue<bool>(nameof(Is_Deleted), ref fIs_Deleted, value); }
        }
    }

}
