//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ResumeBuilder.XPO.Database
{

    public partial class JobSeekerLanguages : XPLiteObject
    {
        int fRId;
        [Key(true)]
        public int RId
        {
            get { return fRId; }
            set { SetPropertyValue<int>(nameof(RId), ref fRId, value); }
        }
        JobSeekerResume fResume_ID;
        [Association(@"JobSeekerLanguagesReferencesJobSeekerResume")]
        public JobSeekerResume Resume_ID
        {
            get { return fResume_ID; }
            set { SetPropertyValue<JobSeekerResume>(nameof(Resume_ID), ref fResume_ID, value); }
        }
        int fLanguage_ID;
        public int Language_ID
        {
            get { return fLanguage_ID; }
            set { SetPropertyValue<int>(nameof(Language_ID), ref fLanguage_ID, value); }
        }
        bool fLanguageRead;
        [ColumnDbDefaultValue("((0))")]
        public bool LanguageRead
        {
            get { return fLanguageRead; }
            set { SetPropertyValue<bool>(nameof(LanguageRead), ref fLanguageRead, value); }
        }
        bool fLanguageWrite;
        [ColumnDbDefaultValue("((0))")]
        public bool LanguageWrite
        {
            get { return fLanguageWrite; }
            set { SetPropertyValue<bool>(nameof(LanguageWrite), ref fLanguageWrite, value); }
        }
        bool fLanguageSpeak;
        [ColumnDbDefaultValue("((0))")]
        public bool LanguageSpeak
        {
            get { return fLanguageSpeak; }
            set { SetPropertyValue<bool>(nameof(LanguageSpeak), ref fLanguageSpeak, value); }
        }
        bool fLanguagecomprehand;
        [ColumnDbDefaultValue("((0))")]
        public bool Languagecomprehand
        {
            get { return fLanguagecomprehand; }
            set { SetPropertyValue<bool>(nameof(Languagecomprehand), ref fLanguagecomprehand, value); }
        }
        bool fIs_Deleted;
        [ColumnDbDefaultValue("((0))")]
        public bool Is_Deleted
        {
            get { return fIs_Deleted; }
            set { SetPropertyValue<bool>(nameof(Is_Deleted), ref fIs_Deleted, value); }
        }
    }

}
