//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ResumeBuilder.XPO.Database
{

    public partial class Pensionfund : XPLiteObject
    {
        int fRID;
        [Key(true)]
        public int RID
        {
            get { return fRID; }
            set { SetPropertyValue<int>(nameof(RID), ref fRID, value); }
        }
        string fNationId;
        [Indexed(Name = @"UC_NationId", Unique = true)]
        [Size(25)]
        public string NationId
        {
            get { return fNationId; }
            set { SetPropertyValue<string>(nameof(NationId), ref fNationId, value); }
        }
        string fDataAccuracy;
        [Size(75)]
        public string DataAccuracy
        {
            get { return fDataAccuracy; }
            set { SetPropertyValue<string>(nameof(DataAccuracy), ref fDataAccuracy, value); }
        }
        string fEmployerName;
        [Size(75)]
        public string EmployerName
        {
            get { return fEmployerName; }
            set { SetPropertyValue<string>(nameof(EmployerName), ref fEmployerName, value); }
        }
        string fEmploymentStatus;
        [Size(75)]
        public string EmploymentStatus
        {
            get { return fEmploymentStatus; }
            set { SetPropertyValue<string>(nameof(EmploymentStatus), ref fEmploymentStatus, value); }
        }
        string fPersonRecordAvailability;
        [Size(75)]
        public string PersonRecordAvailability
        {
            get { return fPersonRecordAvailability; }
            set { SetPropertyValue<string>(nameof(PersonRecordAvailability), ref fPersonRecordAvailability, value); }
        }
        string fStringDateOFBirth;
        [Size(75)]
        public string StringDateOFBirth
        {
            get { return fStringDateOFBirth; }
            set { SetPropertyValue<string>(nameof(StringDateOFBirth), ref fStringDateOFBirth, value); }
        }
        string funifiedNumber;
        [Size(75)]
        public string unifiedNumber
        {
            get { return funifiedNumber; }
            set { SetPropertyValue<string>(nameof(unifiedNumber), ref funifiedNumber, value); }
        }
        string fReason;
        [Size(SizeAttribute.Unlimited)]
        public string Reason
        {
            get { return fReason; }
            set { SetPropertyValue<string>(nameof(Reason), ref fReason, value); }
        }
        bool fIsDeleted1;
        [Persistent(@"IsDeleted")]
        [ColumnDbDefaultValue("((0))")]
        public bool IsDeleted1
        {
            get { return fIsDeleted1; }
            set { SetPropertyValue<bool>(nameof(IsDeleted1), ref fIsDeleted1, value); }
        }
        int fResume_ID;
        public int Resume_ID
        {
            get { return fResume_ID; }
            set { SetPropertyValue<int>(nameof(Resume_ID), ref fResume_ID, value); }
        }
    }

}
