//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ResumeBuilder.XPO.Database
{

    public partial class Reason_Status : XPLiteObject
    {
        long fRID;
        [Key]
        public long RID
        {
            get { return fRID; }
            set { SetPropertyValue<long>(nameof(RID), ref fRID, value); }
        }
        int fReason_ID;
        public int Reason_ID
        {
            get { return fReason_ID; }
            set { SetPropertyValue<int>(nameof(Reason_ID), ref fReason_ID, value); }
        }
        int fStatus_ID;
        public int Status_ID
        {
            get { return fStatus_ID; }
            set { SetPropertyValue<int>(nameof(Status_ID), ref fStatus_ID, value); }
        }
    }

}
