//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ResumeBuilder.XPO.Database
{

    public partial class Reference : XPLiteObject
    {
        long fRID;
        [Key(true)]
        public long RID
        {
            get { return fRID; }
            set { SetPropertyValue<long>(nameof(RID), ref fRID, value); }
        }
        long fResume_ID;
        public long Resume_ID
        {
            get { return fResume_ID; }
            set { SetPropertyValue<long>(nameof(Resume_ID), ref fResume_ID, value); }
        }
        string fReference_Name;
        [Size(55)]
        public string Reference_Name
        {
            get { return fReference_Name; }
            set { SetPropertyValue<string>(nameof(Reference_Name), ref fReference_Name, value); }
        }
        string fCompany_Name;
        [Size(55)]
        public string Company_Name
        {
            get { return fCompany_Name; }
            set { SetPropertyValue<string>(nameof(Company_Name), ref fCompany_Name, value); }
        }
        string fAddress1;
        [Size(80)]
        public string Address1
        {
            get { return fAddress1; }
            set { SetPropertyValue<string>(nameof(Address1), ref fAddress1, value); }
        }
        string fAddress2;
        [Size(80)]
        public string Address2
        {
            get { return fAddress2; }
            set { SetPropertyValue<string>(nameof(Address2), ref fAddress2, value); }
        }
        string fContactNumber;
        [Size(35)]
        public string ContactNumber
        {
            get { return fContactNumber; }
            set { SetPropertyValue<string>(nameof(ContactNumber), ref fContactNumber, value); }
        }
        string fDepartment;
        [Size(55)]
        public string Department
        {
            get { return fDepartment; }
            set { SetPropertyValue<string>(nameof(Department), ref fDepartment, value); }
        }
        string fOccupation;
        [Size(55)]
        public string Occupation
        {
            get { return fOccupation; }
            set { SetPropertyValue<string>(nameof(Occupation), ref fOccupation, value); }
        }
        string fEmailId;
        [Size(35)]
        public string EmailId
        {
            get { return fEmailId; }
            set { SetPropertyValue<string>(nameof(EmailId), ref fEmailId, value); }
        }
        string fUsername;
        [Size(35)]
        public string Username
        {
            get { return fUsername; }
            set { SetPropertyValue<string>(nameof(Username), ref fUsername, value); }
        }
        DateTime fReferenceCreatedDate;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime ReferenceCreatedDate
        {
            get { return fReferenceCreatedDate; }
            set { SetPropertyValue<DateTime>(nameof(ReferenceCreatedDate), ref fReferenceCreatedDate, value); }
        }
        bool fIsDeleted1;
        [Persistent(@"IsDeleted")]
        [ColumnDbDefaultValue("((0))")]
        public bool IsDeleted1
        {
            get { return fIsDeleted1; }
            set { SetPropertyValue<bool>(nameof(IsDeleted1), ref fIsDeleted1, value); }
        }
    }

}
