//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ResumeBuilder.XPO.Database
{

    public partial class Source : XPLiteObject
    {
        long fRID;
        [Key(true)]
        public long RID
        {
            get { return fRID; }
            set { SetPropertyValue<long>(nameof(RID), ref fRID, value); }
        }
        long fResume_ID;
        public long Resume_ID
        {
            get { return fResume_ID; }
            set { SetPropertyValue<long>(nameof(Resume_ID), ref fResume_ID, value); }
        }
        string fSourceName;
        [Size(45)]
        public string SourceName
        {
            get { return fSourceName; }
            set { SetPropertyValue<string>(nameof(SourceName), ref fSourceName, value); }
        }
        string fRelationship;
        [Size(50)]
        public string Relationship
        {
            get { return fRelationship; }
            set { SetPropertyValue<string>(nameof(Relationship), ref fRelationship, value); }
        }
        int fSourceType_ID;
        public int SourceType_ID
        {
            get { return fSourceType_ID; }
            set { SetPropertyValue<int>(nameof(SourceType_ID), ref fSourceType_ID, value); }
        }
        DateTime fSourceLetterDate;
        public DateTime SourceLetterDate
        {
            get { return fSourceLetterDate; }
            set { SetPropertyValue<DateTime>(nameof(SourceLetterDate), ref fSourceLetterDate, value); }
        }
        bool fIsDeleted1;
        [Persistent(@"IsDeleted")]
        [ColumnDbDefaultValue("((0))")]
        public bool IsDeleted1
        {
            get { return fIsDeleted1; }
            set { SetPropertyValue<bool>(nameof(IsDeleted1), ref fIsDeleted1, value); }
        }
        string fReference_Type;
        [Size(2000)]
        public string Reference_Type
        {
            get { return fReference_Type; }
            set { SetPropertyValue<string>(nameof(Reference_Type), ref fReference_Type, value); }
        }
        bool fIsPriority;
        public bool IsPriority
        {
            get { return fIsPriority; }
            set { SetPropertyValue<bool>(nameof(IsPriority), ref fIsPriority, value); }
        }
        DateTime fCreatedDate;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime CreatedDate
        {
            get { return fCreatedDate; }
            set { SetPropertyValue<DateTime>(nameof(CreatedDate), ref fCreatedDate, value); }
        }
        string fCreatedUserName;
        [Size(20)]
        public string CreatedUserName
        {
            get { return fCreatedUserName; }
            set { SetPropertyValue<string>(nameof(CreatedUserName), ref fCreatedUserName, value); }
        }
        DateTime fLastUpdatedDate;
        public DateTime LastUpdatedDate
        {
            get { return fLastUpdatedDate; }
            set { SetPropertyValue<DateTime>(nameof(LastUpdatedDate), ref fLastUpdatedDate, value); }
        }
        string fUpdateUserName;
        [Size(20)]
        public string UpdateUserName
        {
            get { return fUpdateUserName; }
            set { SetPropertyValue<string>(nameof(UpdateUserName), ref fUpdateUserName, value); }
        }
    }

}
