//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ResumeBuilder.XPO.Database
{

    public partial class Status : XPLiteObject
    {
        long fRID;
        [Key]
        public long RID
        {
            get { return fRID; }
            set { SetPropertyValue<long>(nameof(RID), ref fRID, value); }
        }
        string fTitle;
        public string Title
        {
            get { return fTitle; }
            set { SetPropertyValue<string>(nameof(Title), ref fTitle, value); }
        }
        string fTitleAr;
        public string TitleAr
        {
            get { return fTitleAr; }
            set { SetPropertyValue<string>(nameof(TitleAr), ref fTitleAr, value); }
        }
        short fStatusType;
        public short StatusType
        {
            get { return fStatusType; }
            set { SetPropertyValue<short>(nameof(StatusType), ref fStatusType, value); }
        }
        short fStatusImageIndex;
        public short StatusImageIndex
        {
            get { return fStatusImageIndex; }
            set { SetPropertyValue<short>(nameof(StatusImageIndex), ref fStatusImageIndex, value); }
        }
        short fValue;
        public short Value
        {
            get { return fValue; }
            set { SetPropertyValue<short>(nameof(Value), ref fValue, value); }
        }
    }

}
