//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ResumeBuilder.XPO.Database
{

    public partial class Training : XPLiteObject
    {
        long fRID;
        [Key(true)]
        public long RID
        {
            get { return fRID; }
            set { SetPropertyValue<long>(nameof(RID), ref fRID, value); }
        }
        JobSeekerResume fResume_ID;
        [Association(@"TrainingReferencesJobSeekerResume")]
        public JobSeekerResume Resume_ID
        {
            get { return fResume_ID; }
            set { SetPropertyValue<JobSeekerResume>(nameof(Resume_ID), ref fResume_ID, value); }
        }
        int fTrainingName_ID;
        public int TrainingName_ID
        {
            get { return fTrainingName_ID; }
            set { SetPropertyValue<int>(nameof(TrainingName_ID), ref fTrainingName_ID, value); }
        }
        int fInstituteName_ID;
        public int InstituteName_ID
        {
            get { return fInstituteName_ID; }
            set { SetPropertyValue<int>(nameof(InstituteName_ID), ref fInstituteName_ID, value); }
        }
        int fTrainingCenter_ID;
        public int TrainingCenter_ID
        {
            get { return fTrainingCenter_ID; }
            set { SetPropertyValue<int>(nameof(TrainingCenter_ID), ref fTrainingCenter_ID, value); }
        }
        int fBatch_ID;
        public int Batch_ID
        {
            get { return fBatch_ID; }
            set { SetPropertyValue<int>(nameof(Batch_ID), ref fBatch_ID, value); }
        }
        string fTrainingCode;
        [Size(20)]
        public string TrainingCode
        {
            get { return fTrainingCode; }
            set { SetPropertyValue<string>(nameof(TrainingCode), ref fTrainingCode, value); }
        }
        double fTrainingGrade;
        public double TrainingGrade
        {
            get { return fTrainingGrade; }
            set { SetPropertyValue<double>(nameof(TrainingGrade), ref fTrainingGrade, value); }
        }
        string fCourseTitle;
        [Size(35)]
        public string CourseTitle
        {
            get { return fCourseTitle; }
            set { SetPropertyValue<string>(nameof(CourseTitle), ref fCourseTitle, value); }
        }
        int fTrainingCategory_ID;
        public int TrainingCategory_ID
        {
            get { return fTrainingCategory_ID; }
            set { SetPropertyValue<int>(nameof(TrainingCategory_ID), ref fTrainingCategory_ID, value); }
        }
        int fTrainingVenue_ID;
        public int TrainingVenue_ID
        {
            get { return fTrainingVenue_ID; }
            set { SetPropertyValue<int>(nameof(TrainingVenue_ID), ref fTrainingVenue_ID, value); }
        }
        int fStage_ID;
        public int Stage_ID
        {
            get { return fStage_ID; }
            set { SetPropertyValue<int>(nameof(Stage_ID), ref fStage_ID, value); }
        }
        double fTrainingScore;
        public double TrainingScore
        {
            get { return fTrainingScore; }
            set { SetPropertyValue<double>(nameof(TrainingScore), ref fTrainingScore, value); }
        }
        int fProgrameName_ID;
        public int ProgrameName_ID
        {
            get { return fProgrameName_ID; }
            set { SetPropertyValue<int>(nameof(ProgrameName_ID), ref fProgrameName_ID, value); }
        }
        DateTime fStartDate;
        public DateTime StartDate
        {
            get { return fStartDate; }
            set { SetPropertyValue<DateTime>(nameof(StartDate), ref fStartDate, value); }
        }
        DateTime fEndDate;
        public DateTime EndDate
        {
            get { return fEndDate; }
            set { SetPropertyValue<DateTime>(nameof(EndDate), ref fEndDate, value); }
        }
        string fComments;
        [Size(SizeAttribute.Unlimited)]
        public string Comments
        {
            get { return fComments; }
            set { SetPropertyValue<string>(nameof(Comments), ref fComments, value); }
        }
        bool fIsDeleted1;
        [Persistent(@"IsDeleted")]
        [ColumnDbDefaultValue("((0))")]
        public bool IsDeleted1
        {
            get { return fIsDeleted1; }
            set { SetPropertyValue<bool>(nameof(IsDeleted1), ref fIsDeleted1, value); }
        }
    }

}
